"""A row a new foreign key points at is written before the key.

``finance_auth_link`` carries the sentinel owner (``user`` id 0) that
standalone rows point at once auth arrives. Its data statement rode at the
END of ``upgrade()``, which was harmless while the revision had no DDL; once
it carries the owner keys (#1217), Postgres validates every existing row on
``ADD CONSTRAINT`` and refuses the ones owned by 0 unless that row already
exists. SQLite would not show it: it adds a key by rebuilding the table and
does not re-validate the rows it copies.
"""

from __future__ import annotations

from pathlib import Path

from aegis.core.migration_generator import _place_data_statements

REVISION = '''"""finance_auth_link

Revision ID: 005
Revises: 004
"""
from alembic import op
import sqlalchemy as sa

revision = "005"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finance_account", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_finance_account_owner_user_id_user", "user", ["owner_user_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
'''


def test_the_sentinel_row_comes_before_the_keys(tmp_path: Path) -> None:
    revision = tmp_path / "005_finance_auth_link.py"
    revision.write_text(REVISION)

    _place_data_statements(tmp_path, ["finance_auth_link"], [revision])

    body = revision.read_text()
    sentinel = body.find("standalone@finance.local")
    key = body.find("create_foreign_key")
    assert sentinel != -1, body
    assert sentinel < key, "the row a key points at is written after the key"
